services:

  consul:
    image: consul:1.15.4
    ports:
      - "8500:80"
    command: agent -dev -client=0.0.0.0 -http-port=80
    networks:
      consul-net:
        ipv4_address: 172.20.4.2
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
      
  dns-forwarder:
    image: internetsystemsconsortium/bind9:9.18
    container_name: dns-forwarder
    ports:
      - "53:53/udp"
    networks:
      consul-net:
        ipv4_address: 172.20.4.3
    volumes:
      - ./dns-forwarder/named.conf:/etc/bind/named.conf
    depends_on:
      consul:
        condition: service_healthy

  traefik:
    image: traefik:v2.11
    ports:
      - "8088:80"
      - "8081:8080"
    command:
      - "--providers.consulCatalog.endpoint.address=172.20.4.2:80"
      - "--providers.consulCatalog.endpoint.scheme=http"
      - "--providers.consulCatalog.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
    networks:
      consul-net:
        ipv4_address: 172.20.4.4
    depends_on:
      consul:
        condition: service_healthy
    dns:
      - 172.20.4.3
      - 8.8.8.8

  datetime-1:
    build:
      context: ./datetime_service
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - CONSUL_NAME_SERVICE=datetime-1
      - CONSUL_HOST=172.20.4.2
      - CONSUL_PORT=80
    networks:
      consul-net:
        ipv4_address: 172.20.4.5
    dns:
      - 172.20.4.3
      - 8.8.8.8
    depends_on:
      consul:
        condition: service_healthy
  
  datetime-2:
    build:
      context: ./datetime_service
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - CONSUL_NAME_SERVICE=datetime-2
      - CONSUL_HOST=172.20.4.2
      - CONSUL_PORT=80
    networks:
      consul-net:
        ipv4_address: 172.20.4.6
    dns:
      - 172.20.4.3
      - 8.8.8.8
    depends_on:
      consul:
        condition: service_healthy
  
  ubuntu-test:
    build:
      context: ./ubuntu_test
    networks:
      consul-net:
        ipv4_address: 172.20.4.7
    dns:
      - 172.20.4.3
      - 8.8.8.8
    depends_on:
      consul:
        condition: service_healthy
    
networks:
  consul-net:
    name: consul-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.4.0/24
      
