networks:
  saga-orchestration-net:
    name: saga-orchestration-net
    driver: bridge
    ipam:
        config:
          - subnet: 172.20.1.0/24
  

  

volumes:
  conductor_data: {}
  conductor_logs: {}

services:
  conductor:
    image: conductoross/conductor-standalone:3.15.0
    container_name: conductor

    ports:
      - "8080:8080"   # API
      - "5000:5000"   # UI

    networks:
      saga-orchestration-net:
        ipv4_address: 172.20.1.11

    volumes:
      - conductor_data:/app/data
      - conductor_logs:/app/logs
    
    restart: unless-stopped 
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 20s

  # order:
  #   build: order-service

  #   ports:
  #     - "9000:9000"
  #   networks:
  #     saga-orchestration-net:
  #       ipv4_address: 172.20.1.12

  #   environment:
  #     - CONDUCTOR_SERVER_URL=${CONDUCTOR_SERVER_URL}

  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl -f http://localhost:9000/actuator/health" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # inventory:

  # payment: