services:
  math-service:
    build: ./math-service
    container_name: math-service
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    networks:
      observability-math-otlp:
        ipv4_address: 172.20.7.10

networks:
  observability-math-otlp:
    name: observability-math-otlp
    ipam:
      config:
          - subnet: 172.20.7.0/24