global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'stress_test'
    static_configs:
      - targets:
          - 172.20.6.10:8000

# rate(process_cpu_seconds_total{job="stress_test"}[1m])